### ISSUE TITLE
original source.. :)

### ISSUE THREAD

**Issue by byrnecode** [mbj36/vue-burger-menu#10]
Hi, I appreciate this project and want to fully support it. But I find it odd that there was no mention of **tympanus/codrops** where the [original frontend ui](https://tympanus.net/codrops/2014/09/16/off-canvas-menu-effects/) came from. In this open-source world, it is somewhat a common courtesy to at least mention the source or inspiration of a project, just like any other "vue wrapper" projects. This is just a friendly reminder from a fan of both Vue and Codrops site. Thank you and more power to your projects :)
Edit: I mean on your README only, as I am using an api which shows only readmes in my feed :)

**Comment by shivamluthra** [comment]
Hi, FYI, proper credits along with github links to [OffCanvasMenuEffects](https://github.com/codrops/OffCanvasMenuEffects) and [SidebarTransitions](https://github.com/codrops/SidebarTransitions) are given to Codrops as you SERVE the wrapper. Mentioning it in Readme.md would be a good idea and will be done soon :)

**Comment by mbj36** [comment]
@byrnecode If you see the demo site - https://vue-burger-menu.netlify.com/ , there has been proper mention of original source from start because UI is used only in demo site :)
