### ISSUE TITLE
Feature request - open/Close event

### ISSUE THREAD

**Issue by Epillepsy** [mbj36/vue-burger-menu#11]
Hi,
I would like to have access to the "onClose" and "onOpen" events from my components or the ability to use .sync on the isOpen variable to track when the menu is open or close all the time

**Comment by mbj36** [comment]
@Epillepsy Thanks for the request, I can work on this feature during this weekend

**Comment by Epillepsy** [comment]
I opened a pull request with a simple implementation of the feature, I'm new to Vue.Js so please don't hesistate to criticize my (possibly) naive implementation of the feature

**Comment by mbj36** [comment]
Merged
