### ISSUE TITLE
Mention the events on the README

### ISSUE THREAD

**Issue by mbj36** [mbj36/vue-burger-menu#15]
@Epillepsy Would you like to open a PR mentioning the `openMenu` and `closeMenu` events on README ?

**Comment by Epillepsy** [comment]
@mbj36 my bad, totally forgot about this, I will take care of it today

**Comment by mbj36** [comment]
@Epillepsy Do you think you will be available to take this today ?

**Comment by Epillepsy** [comment]
@mbj36 this is done, sorry for the delay
