### ISSUE TITLE
Scroll Behaviour stops working in Scale Down & Scale Rotate effect

### ISSUE THREAD

**Issue by shivamluthra** [mbj36/vue-burger-menu#17]
The content stops scrolling when Scale Down or Scale Rotate effect is selected and burger menu is opened and closed. A usual workaround can be fixing overflow properties and make the content scroll as soon as the menu is closed back.

**Comment by shivamluthra** [comment]
@mbj36 Please assign me to this :)

**Comment by mbj36** [comment]
Fixed

**Comment by rrodriguze** [comment]
I just had this problem with Scale Down effect, maybe this should be revised.
