### ISSUE TITLE
Add UMD support

### ISSUE THREAD

**Issue by mbrodala** [mbj36/vue-burger-menu#21]
It would be great if the dist file (`vue-burger-menu.common.js`) had UMD support to e.g. load this component via RequireJS.

**Comment by mbj36** [comment]
@mbrodala I will have this by tomorrow, thanks for opening the issue

**Comment by mbj36** [comment]
Hey @mbrodala i just published 1.0.7 with umd support

**Comment by mbrodala** [comment]
Thanks, seems to load fine now.
