### ISSUE TITLE
Overlay should be on top of body elements except the sidebar.

### ISSUE THREAD

**Issue by vishnumanjunath** [mbj36/vue-burger-menu#23]
I'm trying to override `.bm-overlay` by add extra `z-index` to it. I'm not able to add my extra styling. I guess this is probably because `.bm-overlay` will be added when the menu is open. Is there anyway to add my style to it?

**Comment by vishnumanjunath** [comment]
Simple I just want to display logo behind overlay. Whenever it is present.

**Comment by ihojmanb** [comment]
Note that if you are styling within a `scoped` style tag you are not going to achieve what you want. 
In your component (header.vue I suppose ) you could add another `<style>` block besides `<style scoped>` block with the vue-burger-menu classes.

**Comment by vishnumanjunath** [comment]
Well, that works I can override the css class, but the issue is, overlay is adding to the body tag because of which elements or on top of it (which should be the opposite). Overlay should be on top of other elements except the sidebar. Sorry for miss guiding I have updated the issue.
