### ISSUE TITLE
Override or Change CSS

### ISSUE THREAD

**Issue by mlangone** [mbj36/vue-burger-menu#28]
What would you recommend the best way is to override or change the css? It appears your css load on page after my app styles.

**Comment by mbj36** [comment]
Is it possible for you to make a short demo so that i can investigate ?

**Comment by mritunjaygoutam12** [comment]
you can simply try by adding style to your component in which you are importing "vue-burger-menu".
if this does not work for you try adding style in mounted function.

Best is if you can provide test case.
> Is it possible for you to make a short reproduction so that i can investigate ?

**Comment by mlangone** [comment]
Adding class to "slide" allows me to target the css thank you.
