### ISSUE TITLE
Programatically open/close nav?

### ISSUE THREAD

**Issue by ptdev** [mbj36/vue-burger-menu#33]
Hi, 
Is there anyway to open and close the drawer programatically?
For example, in case we need to use another button or link instead of the built-in hamburger menu?
Thank you.

**Comment by mbj36** [comment]
There is a hacky way i just tried here - https://codesandbox.io/s/xo0976yq5z

You can use `isOpen` and set the state. Let me know if it works for you.

**Comment by ptdev** [comment]
Great! That was exactly what I needed. 👍 
Thanks for the quick reply, and thanks for releasing this component.

**Comment by Pixney-William** [comment]
Personally i think it's better to just disable both icons using:
`<Slide :burgerIcon="false" :crossIcon="false"/>`

And only use custom elements combined with isOpen

**Comment by aske-cph** [comment]
This doesn't work? I am changing from false to true and back again but nothing happens.
`:isOpen=openState`
Also the above codeSandbox doesn't work either. 
Am i misunderstanding something? Thanks!

**Comment by roonie007** [comment]
@aske-cph  can you share some of the code ? because it works good for me

**Comment by aske-cph** [comment]
Check the codesandbox link: https://codesandbox.io/s/xo0976yq5z

Nothing happens when i click open menu button. In both Chrome and Safari. Does it open for you? For me it only closes an already open menu.

**Comment by roonie007** [comment]
There is a problem with the button, check this https://codesandbox.io/s/10ykw3286q, it's working perfectly

**Comment by roonie007** [comment]
check this https://codesandbox.io/s/wq3ozkvjyl, you need to add e.preventDefault() and e.stopPropagation() to the methods, codesandbox is having a problem with buttons, i don't know why, but another person the otherday  had the same issue as you, https://github.com/mbj36/vue-burger-menu/issues/43#issuecomment-463233677 and it's a sandbox problem.

**Comment by aske-cph** [comment]
Thanks abunch @roonie007 ! I got it working.
