### ISSUE TITLE
Overlay usability suggestion

### ISSUE THREAD

**Issue by ptdev** [mbj36/vue-burger-menu#34]
Hi, I'm having some issues with this component's overlay and overlay close functionality that I'll try to explain and leave a suggestion.

Assumptions about the overlay:
- when the menu is open, the overlay should, well... overlay the rest of the page.
- when clicking the overlay, the menu should close and nothing else. (i.e: should not follow links under the overlay)
- adjusting the opacity of the overlay element should allow us to control the level of darkness of the entire website outside the menu.

What's actually happening:
- when the menu is open, the overlay is simply a "bm-overlay" class on the body element.
- with the menu open, we're allowed to click on links outside the sidebar. (we can still close only the menu by clicking some "blank" part of the webpage, but accidentally clicking a link to close the menu will follow that link)
- adjusting the opacity of the overlay with css, doesn't have the pretended effect, since all it does is change the opacity of the body element's background, which is usually the bottom element on the Z axis.

So my suggestion is that the overlay should be an actual div element that gets added and removed from the body.
This would allow:
- the opacity to work on the entire site (outside the menu).
- call preventDefault and/or stopPropagation (or the equivalent .prevent and .stop vue event modifiers) to avoid having clicks on the overlay be registered by stuff under the overlayed page.
- use z-index to control overlay order.

You can get some good examples of overlays by seeing the overlay from [vuetify's navigation drawers](https://vuetifyjs.com/en/components/navigation-drawers#example-temporary) or [bootstrap's modals](https://getbootstrap.com/docs/4.0/components/modal/#live-demo)

Just a suggestion. Thanks again for releasing this component.

**Comment by ptdev** [comment]
Hey, me again with another suggestion follow-up. Please don't take these the wrong way, they're simple suggestions to make this component more adequate for use across a different variety of sites and markup so you may or may not want to put them in the roadmap. I may eventually fix these myself and submit a pull request if needed, but unfortunately i don't currently have much time for it.

So, although this is called vue-burger-menu, the main functionality is actually the drawer part and no menu is actually included.
Because of that, Menu.vue shouldn't be outputting the nav.bm-item-list tag and just place the contents of <slot> directly inside the first level.
The reason for this suggestion is because when using some other type of content (that may not even be a navigation component), the nav element, and particularly the css rules applied on .bm-item-list will mess up with the contents of what gets placed inside the drawer.

Feel free to close these issues at any time.
Cheers.

**Comment by mbj36** [comment]
Really appreciate your suggestions. Happy to accept PR to improve things

**Comment by Pixney-William** [comment]
Adding to this, since i saw that you submitted a pull request. Could you make sure that isOpen is set to false when you click on the overlay to close the menu as well?

Otherwise, if you are programmatically opening and closing the drawer without using the built in hamburger menu, you need to listen to the close event and set isOpen yourself to false.

**Comment by ptdev** [comment]
Good point, I'll update my pull request to account for that once I get home in an hour or two.

**Comment by ptdev** [comment]
Hey, sorry I couldn't see this yesterday.
Anyway, I took another look at the code and what you're requesting isn't really doable as it stands right now.
That's because isOpen is a prop and we [can't update props directly from outside the component](https://vuejs.org/v2/guide/components-props.html#One-Way-Data-Flow). We could emit an event from a child to the parent component, but that would require that the open button be a child of the slider component, which it probably isn't for custom buttons.
That said, you can still use the example posted by @mbj36 if you also make use of the closeMenu event to update your local "open" variable. [See here](https://codesandbox.io/s/92pq5469mp?module=%2Fsrc%2Fcomponents%2FHelloWorld.vue).
Or better yet, if you're using vuex (which is what I'm using), then you should use that since it's the best way to pass state between components. I also created an example for you with vuex. [See here](https://codesandbox.io/s/y3k0509vr9?module=%2Fsrc%2Fcomponents%2FHelloWorld.vue).
Hope it helps, cheers.
