### ISSUE TITLE
two instaces

### ISSUE THREAD

**Issue by Luis92pe** [mbj36/vue-burger-menu#37]
I try to have two instances in the same component. one Slide component on the left and one on the right. but when I try to open the menu on the left. the one on the right opens.

**Comment by Luis92pe** [comment]
` <Slide id="a">
                 <a id="home" href="#">
                     <span>Home</span>
                 </a>

             </Slide>

             <Slide right>
                 <a id="home" href="#">
                     <span>Home</span>
                 </a>
                 <a id="home" href="#">
                     <span>Home</span>
                 </a>
             </Slide>
`

**Comment by mritunjaygoutam12** [comment]
This feature is not supported right now. we have to operate on Class index basis instead of ID for sidebar opening.

**Comment by NeoMarine** [comment]
I'd also like to be able to create more than 1 instance.

**Comment by roonie007** [comment]
@NeoMarine  with the latest version you can 😄
