### ISSUE TITLE
<Slide right isOpen> has error

### ISSUE THREAD

**Issue by zhousheng193** [mbj36/vue-burger-menu#40]
<Slide right isOpen> has error

**Comment by jacobg213** [comment]
Maybe you should include some more details :)

**Comment by mbj36** [comment]
@zhousheng193 Thanks for reporting, yes i can see errors in console.

Would you like to open a PR ;) ?

I will be able to fix by Monday.

**Comment by zhousheng193** [comment]
![11](https://user-images.githubusercontent.com/5163952/51795611-7db83480-2221-11e9-9a21-d285249f1802.png)
![22](https://user-images.githubusercontent.com/5163952/51795612-827ce880-2221-11e9-885c-48c1c0199332.png)

**Comment by mbj36** [comment]
Should be fixed in v2.0.1
