### ISSUE TITLE
Access to openMenu() function from parent component

### ISSUE THREAD

**Issue by HamHamFonFon** [mbj36/vue-burger-menu#42]
Hello,

I'm trying to open the menu from a link external to the slide but it looks like i don't access to the method.
Here's an example (maybe it's not the correct way, i'm beginner with VueJS)

```
<template>
  <Slide :burgerIcon="false" ref="slideMenu">
    <!-- links -->   
  </Slide>
  <OtherComponentExample></OtherComponentExample>
  <span v-on:click="openSlideMenu">
    Text on click...
  </span>
</template>

<script>
  import { Slide } from 'vue-burger-menu'
  import OtherComponentExample from 'my-component'

  export default {
    name: "Example",
    components: {
      OtherComponentExample,
      Slide
    },
    data() {
      return {
        // some data...
      }
    },
    methods: {
      openSlideMenu: function () {
        console.log('Test open menu');
        this.$refs.slideMenu.openMenu();
      }
    }
  }
</script>
```
I want to open the menu with my method openSlideMenu().
Thank you

**Comment by HamHamFonFon** [comment]
Find the solution, in my method `openSlideMenu`  : 
```
this.$refs.slideMenu.$children[0].openMenu();
```
(a bit weird but i think it's how VueJs rules...)

**Comment by mbj36** [comment]
Glad you found it @HamHamFonFon. Actually i need to clear this in docs and make it more efficient.

**Comment by roonie007** [comment]
@HamHamFonFon the right way to do it, is to use a store, and then you should have a variable in state, which define if the slider is opened or no, and then you can access it from anywhere on the app, that's the right way to do it in vuejs

**Comment by aske-cph** [comment]
Hmm. This doesn't seem to work for me. Can we get an elaboration on the trick in the docs, or codepen? Thanks!

**Comment by martinandersen3d** [comment]
this worked for me:

```
     navSidebarOpen(e) {
      e.preventDefault();
      e.stopPropagation();
      this.$refs.slideMenu.$children[0].openMenu();
    }
```
