### ISSUE TITLE
Option Close on Outside click

### ISSUE THREAD

**Issue by roonie007** [mbj36/vue-burger-menu#43]
Add a Prop to the Menu so it could be persistent or no persistent when someone click on the outside of the Menu

**Comment by roonie007** [comment]
just pushed a PR #44

**Comment by mbj36** [comment]
@roonie007 Thanks for PR, i will take a close look this weekend , merge and release it. Keep Contributing!

**Comment by mbj36** [comment]
Merged, released in v2.0.1

**Comment by edum18** [comment]
@mbj36 with this change, I can't programatically open the menu without "disableOutsideClick", but I still want to click outside like before

**Comment by mbj36** [comment]
@edum18 Could you please reproduce on codesandbox - https://codesandbox.io/s/vue?from-embed

CC - @roonie007

**Comment by edum18** [comment]
> @edum18 Could you please reproduce on codesandbox - https://codesandbox.io/s/vue?from-embed
> 
> CC - @roonie007

https://codesandbox.io/embed/xpv7kzwqkz
2 slides, one with disableOutsideClick and other without. What I want to achieve is being able to open slide with a button and close it clicking outside. As you can see, with disableOutsideClick, the menu opens and closes instantly

**Comment by mbj36** [comment]
I see, issue is you are not able to open menu on click of a button without passing the prop `disableOutsideClick`

Open for a PR, would like to fix ?

**Comment by roonie007** [comment]
@mbj36 @edum18 it's not related to this commit in particualrity, i couldn't reproduce the problem in my computer, it works fine on my machine on chrome and firefox, but i get the bug in the sandbox, and it's actually related to the button itself, or i mean to the mouse click of the button.

You need to make the @Click as a function and then add `e.preventPropagation();` and everything will work perfectly.

here is a [sandbox](https://codesandbox.io/embed/38q2jr69l6) with the e.preventPropagation in th method : 

```html
<!-- Template -->
<button @click="openMenuWithoutDisableOutsideClick">
  open without "disableOutsideClick"
</button>
```

```javascript
// Script
openMenuWithoutDisableOutsideClick(e) {
   e.stopPropagation();
   this.isOpen2 = true;
}
```

**Comment by mbj36** [comment]
@roonie007 Thanks for the help! You are awesome

**Comment by edum18** [comment]
> @mbj36 @edum18 it's not related to this commit in particualrity, i couldn't reproduce the problem in my computer, it works fine on my machine on chrome and firefox, but i get the bug in the sandbox, and it's actually related to the button itself, or i mean to the mouse click of the button.
> 
> You need to make the `@Click` as a function and then add `e.preventPropagation();` and everything will work perfectly.
> 
> here is a [sandbox](https://codesandbox.io/embed/38q2jr69l6) with the e.preventPropagation in th method :
> 
> ```
> 
> <button @click="openMenuWithoutDisableOutsideClick">
>   open without "disableOutsideClick"
> </button>
> ```
> 
> ```js
> // Script
> methods: {
>   openMenuWithoutDisableOutsideClick(e) {
>     e.stopPropagation();
>     this.isOpen2 = true;
>   }
> }
> ```

thank you!
