### ISSUE TITLE
Failed to execute 'appendChild' on Nuxt

### ISSUE THREAD

**Issue by IamTinashe** [mbj36/vue-burger-menu#46]
It runs in development, but fails in production. I'm using Nuxt. Please assist
Plugin:
```import Vue from 'vue'
import { Slide } from 'vue-burger-menu'

Vue.component('Slide', Slide)```

nuxt.config.js
```{ src: '~/plugins/vue-burger-menu.js', ssr: false}```

Component:
```<template>
  <Slide>
    <router-link
      :to="'/'"
      title="Home"
      id="Home"
    >
      <span>Home</span>
    </router-link>
    <router-link
      :to="'/profile'"
      title="Profile"
      id="Profile"
    >
      <span>Profile</span>
    </router-link>
    <router-link
      :to="'/blog'"
      title="Blog"
      id="Blog"
    >
      <span>Blog</span>
    </router-link>
    <router-link
      :to="'/photography'"
      title="Photography"
      id="Photography"
    >
      <span>Photography</span>
    </router-link>
    <router-link
      :to="'/social'"
      title="Social"
      id="Social"
    >
      <span>Social</span>
    </router-link>
    <router-link
      :to="'/connect'"
      title="Contact"
      id="Contact"
    >
      <span>Contact</span>
    </router-link>
  </Slide>
</template>```

**Comment by mbj36** [comment]
@IamTinashe Can you check this issue https://github.com/mbj36/vue-burger-menu/issues/9 if it helps you ?

**Comment by IamTinashe** [comment]
Thanks, That's what I did. So when I'm in development it works fine. But in production it doesn't

**Comment by mbj36** [comment]
Not sure what;s wrong then :(  haven't tried Nuxt yet

**Comment by IamTinashe** [comment]
<img width="614" alt="bug" src="https://user-images.githubusercontent.com/27784507/52715150-c0f9fd80-2fac-11e9-8c08-82cbed1de5db.PNG">

[https://www.iamtinashe.io/](url)

**Comment by roonie007** [comment]
I think this is related to #40 and I think you should update the vue-burger-menu to the last version (from yesterday), this commit Commit [fd20b5f](https://github.com/mbj36/vue-burger-menu/pull/44/commits/fd20b5f6bb5176d5797044595c8552ef5d90f140#diff-597f7240e2b769bbd70fb848c323b0d7) in this merge #44  should have fixed that problem

**Comment by mbj36** [comment]
@IamTinashe please check above comment
