### ISSUE TITLE
Not working with latest Nuxt version 2.4.5

### ISSUE THREAD

**Issue by b-jan** [mbj36/vue-burger-menu#47]
I updated Nuxt to the latest version 2.3.6 => 2.4.5
And my Slide drawer menu was not working anymore.

I actually logged the behaviour in both Nuxt versions to understand was happening.
What has changed after the update is that the openMenu() function is now called before the documentClick() function when I click on my custom burger icon. As a result the menu opens and closes immediately. I was unable to solve the issue.

I finally implemented my own simple burger menu.

**Comment by mbj36** [comment]
https://github.com/mbj36/vue-burger-menu/issues/43#issuecomment-463233677 Could you please check this comment ?

Also which version of package you are using ?
