### ISSUE TITLE
Can't style CSS

### ISSUE THREAD

**Issue by adpace** [mbj36/vue-burger-menu#52]
Hello all,
I am not able to override any of the css for the slide css. I've tried adding classes to <Slide>, tried wrapping it and using deep selectors, tried just using the single css class selectors on their own, nothing. Below is a copy of the code where this lives. Any help is appreciated. 

`<template>
    <div class="row">
        <div class="col d-flex">
            <div class="mr-auto mt-3 ml-3">
                <div v-if="userRole">
                    <div v-if="userRole === 'admin' || userRole === 'driver' || userRole === 'industry'">
                        <router-link to="/toc">
                            <logo></logo>
                        </router-link>
                    </div>
                    <div v-else>
                        <router-link to="/" style="cursor: pointer;">
                            <logo></logo>
                        </router-link>
                    </div>
                </div>
                <div v-else>
                    <router-link to="/" style="cursor: pointer;">
                        <logo></logo>
                    </router-link>
                </div>

                
                
                

                <Slide right class="foo"></Slide>

                

            </div>
        </div>
</div>
</template>`

`<script>
    import Logo from '@/components/RufusLogo'
    import { Slide } from 'vue-burger-menu'

    export default {
        name      : 'TheHeader',
        components: {
            Logo,
            Slide
        }...`

`<style scoped lang="scss">
    @import '../assets/css/_vars.scss';

    .bm-burger-button {
        position: fixed;
        width: 30px;
        height: 80px;
        left: 36px;
        top: 16px;
        cursor: pointer;
    }
</style>`

**Comment by mbj36** [comment]
Would appreciate if you can reproduce using CodeSandbox here - https://codesandbox.io/s/vue?from-embed

**Comment by roonie007** [comment]
@mbj36 

it's true, there is a problem with the CSS since it's included as global classes, and sometime it's overwritten in the element Style attribute, maybe we need to check the css implementation and improve it.

i can take a look at it this weekend

**Comment by LaserVisionRj** [comment]
@adpace if you remove scoped from the style it will work

**Comment by GokiSun** [comment]
In the 'pull' methods, I think you ought to remove the styles, which are added in the 'push',rather than change, or they will make some porperties useless, like the 'perspective ' to 'z-index'.
