### ISSUE TITLE
CSS not preserved when building the application

### ISSUE THREAD

**Issue by inderjeetfbd** [mbj36/vue-burger-menu#62]
The changes done to CSS classes (like, .bm-burger-button, .bm-item-list) doesn't work when I build and deploy the application on the server. When checking locally, it works.

Please suggest.

**Comment by daitah** [comment]
I am having the same issue here. any solution ?

**Comment by lukasrump** [comment]
I had the same issue. A quick and dirty solution would be to use the CSS !import property.

**Comment by quantavi** [comment]
@lukasrump as much as I hate having 30+ css lines with !important in single component, this works well as a "quick and dirty" solution. Thanks! 
As for the component, it would be great if you could easily define styling.
