### ISSUE TITLE
isOpen doesn't work

### ISSUE THREAD

**Issue by RomkaLTU** [mbj36/vue-burger-menu#63]
It's just doesn't work at all. 

Passing boolean value to :isOpen="menuState", not working.

**Comment by mbj36** [comment]
Can you reproduce on codesandbox ?

It seems to be working for me here - https://codesandbox.io/s/xo0976yq5z

**Comment by RomkaLTU** [comment]
Ok I figured it out. I need to catch @openMenu event and set menuState to true.

**Comment by Dennisvb** [comment]
@mbj36 I press "Open Menu" on the codesanbox example and nothing happens, but it should, right?

**Comment by madroneropaulo** [comment]
Yeah it doesn't work on the sandbox. Maybe an introduced bug. It worked for me as @RomkaLTU suggested, by using the @openMenu and @closeMenu events algonside with isOpen
