### ISSUE TITLE
isOpen doesn't work 

### ISSUE THREAD

**Issue by Dennisvb** [mbj36/vue-burger-menu#67]
I have the same problem stated in issue #63 and the codesandbox you've replied (https://codesandbox.io/s/xo0976yq5z) doesn't work either for me. When I press "open menu" nothing happens. 

I have noticed that changing "isOpen" to true will trigger the event twice. Once to open, once to close.

Am I doing something wrong?

Dennis

**Comment by jayehernandez** [comment]
Had the same problem! Checked issue #33 and adding `e.stopPropagation()` to the method `openMenu` worked for me. Here's their codesandbox https://codesandbox.io/s/wq3ozkvjyl.
