### ISSUE TITLE
Menu breaks on heroku deploy

### ISSUE THREAD

**Issue by Colin-Moran** [mbj36/vue-burger-menu#68]
I'm using it for my nav-bar in a node/express/vue/mongo app and it looked and works great locally, but when deployed on heroku the menu is completely broken. It will slide out but there is no content on it and its gone back to its default color. Any ideas?

**Comment by Ch3rlO** [comment]
@Colin-Moran  U can use the IMPORTANT keyword in the style 

so it'll be like 

`.text-white-over {
    color: #00b894 !important;
}

.bb-3 {
    border-bottom: 1px solid #00b894 !important;
}

.bg-white-menu {
    background-color: white !important;
}

.bm-burger-button {
    position: fixed !important;
    width: 30px !important;
    height: 20px !important;
    left: 36px !important;
    top: 25px !important;
    right: unset !important;
    cursor: pointer !important;
}

.bm-burger-bars {
    background-color: white !important;
}

.w-32 {
    width: 32px !important;
}

.text-white-over-s {
    color: white !important;
    transition: 0.3s !important;
}

.text-white-over-s:hover {
    color: #707070 !important;
}

.line-style {
    position: absolute !important;
    height: 15% !important;
    left: 0 !important;
    right: 0 !important;
    border-radius: 5px !important;
}

.cross-style {
    position: absolute !important;
    top: 25px !important;
    right: 2px !important;
    cursor: pointer !important;
}

.bm-cross {
    background: #707070 !important;
}

.bm-cross-button {
    height: 24px !important;
    width: 24px !important;
}

.bm-menu {
    height: 100% !important;
    /* 100% Full-height */
    width: 0;
    /* 0 width - change this with JavaScript */
    position: fixed !important;
    /* Stay in place */
    z-index: 1000 !important;
    /* Stay on top */
    top: 0 !important;
    left: 0 !important;
    background-color: #fff !important;
    /* Black*/
    overflow-x: hidden !important;
    /* Disable horizontal scroll */
    padding-top: 60px !important;
    /* Place content 60px from the top */
    transition: 0.5s !important;
    /*0.5 second transition effect to slide in the sidenav*/
}

.bm-overlay {
    background: rgba(0, 0, 0, 0.9) !important;
}

.bm-item-list {
    color: #b8b7ad !important;
    margin-left: 10% !important;
    font-size: 20px !important;
}

.bm-item-list>* {
    display: flex !important;
    text-decoration: none !important;
    padding: 0.7em !important;
}

.bm-item-list>*>span {
    margin-left: 10px !important;
    font-weight: 700 !important;
    color: white !important;
}`

OFC u have to change some stuff cuz I used ltr 

but the point issue it's just the overwrite for the CSS style in the PACKAGE itself  
so u have to put !important whenever u need to overwrite the style

**Comment by mbj36** [comment]
Do you mind opening a PR ?

**Comment by Ch3rlO** [comment]
yup sure
