### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Leviosar** [mbj36/vue-burger-menu#70]
Great job on this component, but do you plan to add Typescript support? Just a type declaration on  npm should do just fine.

**Comment by mbj36** [comment]
Happy to accept PR

**Comment by SergeyKons** [comment]
Hi! We need to use this plugin in our typescript project. So I was written a simple declaration file for it. 

You can find it here. https://gist.github.com/SergeyKons/96067830669ae62aef7fd5aeba9ea640

Later I will publish it to definitely typed
