### ISSUE TITLE
Open side nav manually

### ISSUE THREAD

**Issue by clien007** [mbj36/vue-burger-menu#82]
Hi!

Just want to ask how to open the side nav manually or using javascript?

Thanks!

**Comment by BobSynfig** [comment]
Hi,

You can use a reactive variable like here:
`<Slide :isOpen=slideIsOpen @openMenu=openSlide @closeMenu=closeSlide></Slide>`

```
data() {
    return {
        slideIsOpen : false //Closed at startup
    }
}
```

```
methods: {
    openSlide() {
        this.slideIsOpen = true
    } ,
    closeSlide() {
        this.slideIsOpen = false
    },
    toggleSlide() {
        this.slideIsOpen = !this.slideIsOpen
    }
}
```

and call the wanted method (_this.openSlide()_, _this.closeSlide()_ or _this.toggleSlide()_) from your code :)
