### ISSUE TITLE
Does not work with NUXT

### ISSUE THREAD

**Issue by mingsterism** [mbj36/vue-burger-menu#9]
Hi, 
I tried getting it to work with Nuxt however, facing similar issue to this. 
https://github.com/nuxt/nuxt.js/issues/2241

Is vue-burger-menu SSR friendly? 

Thanks

**Comment by mbj36** [comment]
It does not support SSR at the moment

PRs welcome.

**Comment by mbj36** [comment]
@mingsterism You can use this - https://github.com/egoist/vue-no-ssr

**Comment by jaskiratr** [comment]
To use it in with Nuxt, I had use it as a plugin with no SSR

**plugins/slide-menu.js**
```
import Vue from 'vue'
import { Slide } from 'vue-burger-menu' 
Vue.component('Slide', Slide)
```

**nuxt.config.js**
```
plugins: [ { src: '~plugins/quill-editor', ssr: false }]
```

**index.vue**
```
#app
 no-ssr
    Slide
        a#home(href="#")
          span Home
```

**Comment by mbj36** [comment]
@mritunjaygoutam12 Adding this in WIKI would be good

**Comment by MacZel** [comment]
It is not working with Nuxt because of all recalls to document. In order to make it work all of the components need to be rewritten in such a way that they are not recalling document during server rendering.

**Comment by sbefort** [comment]
This can be changed:
````
import { Slide } from 'vue-burger-menu'
import { ScaleDown } from 'vue-burger-menu'
import { ScaleRotate } from 'vue-burger-menu'
import { Reveal } from 'vue-burger-menu'
import { Push } from 'vue-burger-menu'
import { PushRotate } from 'vue-burger-menu'
```

To this:
```
import { Slide, ScaleDown, ScaleRotate, Reveal, Push, PushRotate } from 'vue-burger-menu';
```

**Comment by szvest** [comment]
Has anyone made it work as @jaskiratr explained? It throws 'document is not defined' error :
```
var styleElement = document.querySelector('style[' + ssrIdKey + '~="' + obj.id + '"]')
```

**Comment by szvest** [comment]
Ok.. fixed. 
```
Vue.component('Slide', Slide)
```
instead of 
```
Vue.component('SlideMenu', Slide)
```

**Comment by Qvatra** [comment]
@jaskiratr,
I use plugin slideMenu.js:
```
import Vue from 'vue'
import { Slide, ScaleDown, ScaleRotate, Reveal, Push, PushRotate } from 'vue-burger-menu'

Vue.component('SlideMenu', Slide)
Vue.component('ScaleDownMenu', ScaleDown)
Vue.component('ScaleRotateMenu', ScaleRotate)
Vue.component('RevealMenu', Reveal)
Vue.component('PushMenu', Push)
Vue.component('PushRotateMenu', PushRotate)
```

and register it
```
  plugins: [
    { src: '@/plugins/slideMenu.js', ssr: false }
  ],
```
and in template I have:
```
<template>
  <div class="_desktop-layout">
    <no-ssr placeholder="loading...">
      <Slide>
        <a id="home" href="#">
          <span>Home</span>
        </a>
      </Slide>
    </no-ssr>
</template>
```
and It works! no 'no document' errors anymore.
but still have error in the console:

```
commons.app.js:12032 [Vue warn]: Unknown custom element: <Slide> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

found in

---> <Desktop> at layouts/desktop.vue
       <Root>
```

Did someone have to deal with it as well it?

**Comment by allisonaraujoo** [comment]
The error still persists. Help me >>>> document is not defined

**Comment by xdiegom** [comment]
@allisonaraujoo I just did as @sbefort  said to implement and it worked.
Nuxt Version: 2.12.1

**Comment by nynevi** [comment]
@allisonaraujoo make sure to remove Slide (or whichever you are using) from your component's components property. 

Slide would be global via the plugin

**Comment by git-e-001** [comment]
In Nuxt 3 you can use this in your plugin folder `vue3-burger-menu.client.js`
```
import { Slide } from 'vue3-burger-menu'
export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.component('Slide', Slide)
})

```
